branch-defaults:
  default:
    environment: flask-env
    group_suffix: null
global:
  application_name: json-webservice
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 2.7
  default_region: ap-southeast-2
  profile: eb-cli
  repository: null
  sc: null
